name: Check

on: 
  push:
    branches-ignore:    
      - 'main'
      - 'releases/**'

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      engine:
        image: authkit/enginestub:0.9.0
        environment:
          STUB_HTTP_HOST: 0.0.0.0
          STUB_URL: http://localhost:9996
          STUB_USERS: /etc/users.json
        volumes:
          - ./users.json:/etc/users.json
        ports:
          - 9996:8080
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: check
