name: Check

on: 
  push:
    branches-ignore:    
      - 'main'
      - 'releases/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run dev containers
        run: |
          docker-compose up -d
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://localhost:9996/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: check
