name: Release

on: 
  push:
    branches:    
      - 'main'
      - 'releases/**'

jobs:
  release:
    runs-on: ubuntu-latest
    services:
      engine:
        image: authkit/enginestub:0.9.0
        environment:
          STUB_HTTP_HOST: 0.0.0.0
          STUB_URL: http://localhost:9996
          STUB_USERS: /etc/users.json
        volumes:
          - ./users.json:/etc/users.json
        ports:
          - 9996:8080
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Environment Setup
        run: |
          git config --global user.email "release@authkit.com"
          git config --global user.name "AuthKit Release"
          gpg --export-secret-keys -o ~/.gnupg/secring.gpg
          mkdir ~/.gradle
          echo "sonatypeUsername=$SONATYPE_USERNAME" >> ~/.gradle/gradle.properties
          echo "sonatypePassword=$SONATYPE_PASSWORD" >> ~/.gradle/gradle.properties
          echo "signing.keyId=8D1B668F" >> ~/.gradle/gradle.properties
          echo "signing.password=" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=$HOME/.gnupg/secring.gpg" >> ~/.gradle/gradle.properties
          ls -l ~/.gnupg
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: check release
